### ISSUE TITLE
String Decimals Being Returned in Substrate Error Handling

### ISSUE THREAD

**Issue by kristian1108** [polkascan/py-substrate-interface#211] opened 2022-04-20 01:50 UTC
In the Westend runtime, error codes are bring returned as string decimals on occasion which is breaking the provided error parsing logic. 

See question and answer in the Substrate stack exchange: https://substrate.stackexchange.com/questions/1972/0x02000000-being-returned-in-extrinsic-receipt-and-failing-error-module-indexing

**Comment by arjanz** [comment] 2022-04-25 10:53
This is indeed caused by recently released PR https://github.com/paritytech/substrate/pull/10242, the change in error message format needs to implemented in the lib as well, I'll follow up on this

**Comment by arjanz** [comment] 2022-04-26 12:45
Fix released in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.2.4

**Closed** 2022-05-04 16:25 UTC
